services:
  - type: web
    name: bookmembers-app
    env: docker
    plan: starter
    branch: main
    autoDeploy: true
    healthCheckPath: /keep-alive
    envVars:
      - key: NOTION_PUBLIC_WIKI_URL
        value: https://quaint-sapphire-900.notion.site/bookbook
      - key: PUBLIC_BASE_URL
        value: https://book-member-maker.onrender.com
