const assert = require('node:assert/strict');
const {TopicDraftStore} = require('../static/topic_drafts.js');
const {dateLabel} = require('../static/seminar_schedule.js');
const data = new Map();
const storage = {getItem: k => data.get(k) ?? null, setItem: (k,v) => data.set(k,v), removeItem: k => data.delete(k)};
let now = 1000;
const store = new TopicDraftStore(storage, () => now);
const topics = [{topic: '복구할 질문', page: '12', reference: '인용'}];
assert.equal(store.save('event', 'person', topics), true);
assert.deepEqual(store.read('event', 'person').draft.topics, topics);
assert.equal(store.read('other-event', 'person').draft, null);
assert.equal(store.read('event', 'other-person').draft, null);
assert.equal(store.remove('event', 'person'), true);
assert.equal(store.read('event', 'person').draft, null);
store.save('event', 'person', topics);
now += 7 * 86400000 + 1;
assert.equal(store.read('event', 'person').draft, null);
data.set(store.key('event', 'person'), '{broken');
assert.equal(store.read('event', 'person').ok, false);
const blocked = new TopicDraftStore({getItem() {throw Error('blocked');}, setItem() {throw Error('quota');}, removeItem() {throw Error('blocked');}});
assert.equal(blocked.read('event','person').ok, false);
assert.equal(blocked.save('event','person',topics), false);
assert.equal(blocked.remove('event','person'), false);
assert.equal(dateLabel('2026-09-23'), '2026-09-23 (수)');
assert.equal(dateLabel('2026-09-28'), '2026-09-28 (월)');
assert.equal(dateLabel(''), '');
console.log('Draft persistence, identity/event isolation, expiry, storage failure, and actual weekdays passed.');
