const assert = require('node:assert/strict');
const {GroupEditorState, pairHistory} = require('../static/group_editor.js');

const state = new GroupEditorState({groups:[['가','나'],['다']], participants:['가','나','다'], facilitators:['가']});
assert.equal(state.dirty, false);
state.move('나', 1);
assert.deepEqual(state.groups, [['가'],['다','나']]);
assert.equal(state.dirty, true);
assert.deepEqual(state.payload().present, ['가','다','나']);
assert.deepEqual(state.unassigned, []);
state.move('가', 'unassigned');
assert.deepEqual(state.unassigned, ['가']);
assert.match(state.error(), /미배정/);
state.exclude('가', '개인 사정');
assert.deepEqual(state.excluded, [{name:'가',reason:'개인 사정'}]);
assert.deepEqual(state.payload().facilitators, []);
assert.deepEqual(state.unassigned, []);
assert.match(state.error(), /빈 조/);
state.removeGroup(0);
assert.equal(state.error(), '');
const restored = new GroupEditorState({...state.payload(), ...state.payload().group_editor_state});
assert.deepEqual(restored.excluded, [{name:'가',reason:'개인 사정'}]);
state.move('가', 'unassigned');
assert.deepEqual(state.unassigned, ['가']);
assert.equal(state.excluded.length, 0);
state.undo();
assert.equal(state.excluded.length, 1);
state.markSaved();
assert.equal(state.dirty, false);
state.removeGroup(0);
assert.deepEqual(state.unassigned.sort(), ['나','다']);
state.undo();
assert.deepEqual(state.groups, [['다','나']]);
state.move('외부 이름', 0);
assert.deepEqual(state.groups, [['다','나']]);
state.move('다', 100);
assert.deepEqual(state.groups, [['다','나']]);
state.addParticipant('라');
assert.deepEqual(state.unassigned, ['라']);
state.move('라', 0);
assert.equal(state.error(), '');
assert.deepEqual(pairHistory(['나','가','다'], {'가-나':{count:2,dates:['2026-08-27','2026-08-20']}}), {
    known:[{pair:['가','나'],count:2,dates:['2026-08-27','2026-08-20']}],fresh:2
});
const duplicates = new GroupEditorState({groups:[['가'],['가']]});
assert.match(duplicates.error(), /여러 번/);
const named = new GroupEditorState({groups:[['가'],['나']], groupNames:['사과조','배조']});
named.removeGroup(0);
assert.deepEqual(named.groupNames, ['배조']);
assert.deepEqual(named.payload().group_editor_state.group_names, ['배조']);
named.undo();
assert.deepEqual(named.groupNames, ['사과조','배조']);
console.log('Group editor state: move, unassign, exclusion restore, undo, persistence, counts, pair history passed.');
