-- Canonical legacy baseline for local Supabase rebuilds.
-- Schema-only: contains no production member or activity rows.
-- The source definitions were audited against project lzvfkbekhbcqfbknldmo on 2026-09-01.
-- Existing migrations/ files remain the historical reference; new work uses supabase/migrations/.

begin;

create table public.members (
  id bigint generated BY DEFAULT as identity not null,
  name text not null,
  gender text,
  preferred text,
  avoided text,
  notes text,
  social_id text,
  email text,
  profile_pic text,
  role text default 'member'::text,
  profile_intro text,
  profile_mbti text,
  profile_interests text,
  profile_content text,
  is_active boolean default true,
  account_status text default 'pending'::text,
  demerit_points integer default 0 not null,
  recruiting_class integer,
  member_status text default 'active'::text,
  student_id text,
  department text,
constraint members_pkey primary key (id),
constraint members_email_key unique (email)
);

create table public.events (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  event_name text,
  start_date date,
  end_date date,
  is_active boolean default true,
  share_token text,
constraint events_pkey primary key (id)
);

create table public.interviewers (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  name text,
  contact text,
constraint interviewers_pkey primary key (id)
);

create table public.applicants (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  name text,
  phone_number text,
constraint applicants_pkey primary key (id),
constraint applicants_phone_number_key unique (phone_number)
);

create table public.history (
  id uuid default gen_random_uuid() not null,
  date text not null,
  present jsonb,
  facilitators jsonb,
  groups jsonb,
constraint history_pkey primary key (id)
);

create table public.bookclub_co_matrix (
  id uuid default gen_random_uuid() not null,
  pair_key text not null,
  count bigint,
  last_met date,
constraint bookclub_co_matrix_pkey primary key (id)
);

create table public.attendance (
  id bigint generated BY DEFAULT as identity not null,
  user_id bigint,
  meeting_date date not null,
  created_at timestamp with time zone default now() not null,
  attending_seminar boolean default true,
  attending_afterparty boolean default true,
  absence_reason text,
  absence_request_status text default 'none'::text,
constraint attendance_pkey primary key (id),
constraint attendance_user_id_fkey foreign key (user_id) references public.members(id) on delete cascade,
constraint attendance_user_meeting_unique unique (user_id, meeting_date)
);

create table public.questions (
  id bigint generated BY DEFAULT as identity not null,
  user_id bigint,
  meeting_date date not null,
  content text not null,
  created_at timestamp with time zone default now() not null,
constraint questions_pkey primary key (id),
constraint questions_user_id_fkey foreign key (user_id) references public.members(id) on delete cascade,
constraint questions_content_check check (char_length(content) > 0)
);

create table public.documents (
  id bigint generated BY DEFAULT as identity not null,
  title text not null,
  content text,
  author_id bigint,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
constraint documents_pkey primary key (id),
constraint documents_title_key unique (title),
constraint documents_author_id_fkey foreign key (author_id) references public.members(id) on delete set null
);

create table public.document_logs (
  id bigint generated BY DEFAULT as identity not null,
  document_id bigint,
  editor_id bigint,
  content text,
  created_at timestamp with time zone default now() not null,
constraint document_logs_pkey primary key (id),
constraint document_logs_document_id_fkey foreign key (document_id) references public.documents(id) on delete cascade,
constraint document_logs_editor_id_fkey foreign key (editor_id) references public.members(id) on delete set null
);

create table public.notifications (
  id bigint generated BY DEFAULT as identity not null,
  type text not null,
  status text default 'pending'::text not null,
  related_member_id bigint,
  details jsonb,
  created_at timestamp with time zone default now() not null,
constraint notifications_pkey primary key (id),
constraint notifications_related_member_id_fkey foreign key (related_member_id) references public.members(id) on delete cascade
);

create table public.topic_events (
  id uuid default gen_random_uuid() not null,
  meeting_date date not null,
  book_title varchar not null,
  share_token varchar not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()),
constraint topic_events_pkey primary key (id),
constraint topic_events_share_token_key unique (share_token)
);

create table public.topic_submissions (
  id uuid default gen_random_uuid() not null,
  event_id uuid,
  author_name varchar not null,
  department varchar not null,
  pin_code varchar not null,
  topics jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
constraint topic_submissions_pkey primary key (id),
constraint topic_submissions_event_id_fkey foreign key (event_id) references public.topic_events(id) on delete cascade,
constraint topic_submissions_event_id_author_name_department_key unique (event_id, author_name, department)
);

create table public.time_slots (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  event_id uuid,
  slot_datetime timestamp with time zone,
  is_booked boolean default false,
  is_active boolean default true,
  interviewer_ids uuid[],
constraint time_slots_pkey primary key (id),
constraint time_slots_event_id_fkey foreign key (event_id) references public.events(id) on delete cascade
);

create table public.reservations (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  slot_id uuid,
  applicant_id uuid,
  is_cancelled boolean default false,
constraint reservations_pkey primary key (id),
constraint reservations_slot_id_fkey foreign key (slot_id) references public.time_slots(id) on delete restrict,
constraint reservations_applicant_id_fkey foreign key (applicant_id) references public.applicants(id) on delete restrict,
constraint reservations_slot_id_key unique (slot_id)
);

create or replace function public.increment_demerit(member_id_in integer, points_in integer)
returns void
language sql
security invoker
set search_path = ''
as $function$
  update public.members
  set demerit_points = demerit_points + points_in
  where id = member_id_in;
$function$;

create or replace function public.decrement_demerit(member_id_in integer, points_in integer)
returns void
language sql
security invoker
set search_path = ''
as $function$
  update public.members
  set demerit_points = greatest(0, demerit_points - points_in)
  where id = member_id_in;
$function$;

revoke all on function public.increment_demerit(integer, integer) from public, anon, authenticated;
revoke all on function public.decrement_demerit(integer, integer) from public, anon, authenticated;
grant execute on function public.increment_demerit(integer, integer) to service_role;
grant execute on function public.decrement_demerit(integer, integer) to service_role;

alter table public.members enable row level security;
revoke all on table public.members from public, anon, authenticated;
grant select, insert, update, delete on table public.members to service_role;
alter table public.events enable row level security;
revoke all on table public.events from public, anon, authenticated;
grant select, insert, update, delete on table public.events to service_role;
alter table public.interviewers enable row level security;
revoke all on table public.interviewers from public, anon, authenticated;
grant select, insert, update, delete on table public.interviewers to service_role;
alter table public.applicants enable row level security;
revoke all on table public.applicants from public, anon, authenticated;
grant select, insert, update, delete on table public.applicants to service_role;
alter table public.history enable row level security;
revoke all on table public.history from public, anon, authenticated;
grant select, insert, update, delete on table public.history to service_role;
alter table public.bookclub_co_matrix enable row level security;
revoke all on table public.bookclub_co_matrix from public, anon, authenticated;
grant select, insert, update, delete on table public.bookclub_co_matrix to service_role;
alter table public.attendance enable row level security;
revoke all on table public.attendance from public, anon, authenticated;
grant select, insert, update, delete on table public.attendance to service_role;
alter table public.questions enable row level security;
revoke all on table public.questions from public, anon, authenticated;
grant select, insert, update, delete on table public.questions to service_role;
alter table public.documents enable row level security;
revoke all on table public.documents from public, anon, authenticated;
grant select, insert, update, delete on table public.documents to service_role;
alter table public.document_logs enable row level security;
revoke all on table public.document_logs from public, anon, authenticated;
grant select, insert, update, delete on table public.document_logs to service_role;
alter table public.notifications enable row level security;
revoke all on table public.notifications from public, anon, authenticated;
grant select, insert, update, delete on table public.notifications to service_role;
alter table public.topic_events enable row level security;
revoke all on table public.topic_events from public, anon, authenticated;
grant select, insert, update, delete on table public.topic_events to service_role;
alter table public.topic_submissions enable row level security;
revoke all on table public.topic_submissions from public, anon, authenticated;
grant select, insert, update, delete on table public.topic_submissions to service_role;
alter table public.time_slots enable row level security;
revoke all on table public.time_slots from public, anon, authenticated;
grant select, insert, update, delete on table public.time_slots to service_role;
alter table public.reservations enable row level security;
revoke all on table public.reservations from public, anon, authenticated;
grant select, insert, update, delete on table public.reservations to service_role;

-- Historical untracked migrations folded into the baseline.

-- ===== 001_seminar_voting.sql =====

-- 세미나 출석 투표 시스템 (학기 단위)
-- Supabase SQL 에디터에서 실행하세요.

-- 1) 학기
create table if not exists seminar_terms (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  start_date date not null,
  end_date date not null,
  share_token uuid not null default gen_random_uuid() unique,
  max_capacity int not null default 32,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

-- 2) 회차 (월/목 각각)
create table if not exists seminar_sessions (
  id uuid primary key default gen_random_uuid(),
  term_id uuid not null references seminar_terms(id) on delete cascade,
  meeting_date date not null,
  day_type text not null check (day_type in ('mon','thu')),
  is_active boolean not null default true,
  unique (term_id, meeting_date)
);
create index if not exists seminar_sessions_meeting_date_idx
  on seminar_sessions(meeting_date);

-- 3) 투표
create table if not exists seminar_votes (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references seminar_sessions(id) on delete cascade,
  member_id bigint not null references members(id) on delete cascade,
  attending boolean not null,
  voted_at timestamptz default now(),
  unique (session_id, member_id)
);
create index if not exists seminar_votes_session_attending_idx
  on seminar_votes(session_id, attending);


-- ===== 002_records_system.sql =====

-- 통합 기록 시스템 v2 (단순화)
-- Supabase SQL 에디터에서 실행하세요.

-- 1) 장르 마스터
create table if not exists genres (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  is_default boolean not null default false,
  display_order int default 100,
  created_at timestamptz default now()
);
insert into genres (name, is_default, display_order) values
  ('고전문학', true, 10),
  ('한국문학', true, 20),
  ('비문학',   true, 30),
  ('시',       true, 40)
on conflict (name) do nothing;

-- 2) history 확장
alter table history add column if not exists book_title text;
alter table history add column if not exists genre text;

-- 3) 벽돌책 그룹 (책 단위)
create table if not exists brick_books (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  notes text,
  created_at timestamptz default now()
);

-- 4) 벽돌책 세션 (날짜별 모임)
create table if not exists brick_book_sessions (
  id uuid primary key default gen_random_uuid(),
  brick_book_id uuid not null references brick_books(id) on delete cascade,
  meeting_date date not null,
  notes text,
  created_at timestamptz default now()
);
create index if not exists brick_book_sessions_book_idx on brick_book_sessions(brick_book_id);
create index if not exists brick_book_sessions_date_idx on brick_book_sessions(meeting_date);

-- 5) 벽돌책 세션 참여자
create table if not exists brick_session_members (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references brick_book_sessions(id) on delete cascade,
  member_id bigint not null references members(id) on delete cascade,
  unique (session_id, member_id)
);
create index if not exists brick_session_members_member_idx on brick_session_members(member_id);

-- 6) 소모임 그룹
create table if not exists study_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  notes text,
  created_at timestamptz default now()
);

-- 7) 소모임 세션
create table if not exists study_group_sessions (
  id uuid primary key default gen_random_uuid(),
  study_group_id uuid not null references study_groups(id) on delete cascade,
  meeting_date date not null,
  notes text,
  created_at timestamptz default now()
);
create index if not exists study_group_sessions_group_idx on study_group_sessions(study_group_id);
create index if not exists study_group_sessions_date_idx on study_group_sessions(meeting_date);

-- 8) 소모임 세션 참여자
create table if not exists study_session_members (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references study_group_sessions(id) on delete cascade,
  member_id bigint not null references members(id) on delete cascade,
  unique (session_id, member_id)
);
create index if not exists study_session_members_member_idx on study_session_members(member_id);


-- ===== 003_seminar_book.sql =====

-- 003: 회차별 책 정보 + 관리자가 투표 마감 후에도 수동 추가/제거하기 위한 컬럼

alter table seminar_sessions
  add column if not exists book_title text;

-- 관리자 수동 추가 투표 추적용 (선택적)
alter table seminar_votes
  add column if not exists added_by_admin boolean not null default false;


-- ===== 004_improvements.sql =====

-- 004_improvements.sql
-- Schema/index improvements + bug fix
--
-- 적용 순서대로 Supabase SQL 콘솔에서 실행하세요.
-- 각 섹션은 독립적으로 실행 가능하며, 이미 적용된 항목은 IF NOT EXISTS로 안전하게 스킵됩니다.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) [BUG FIX] bookclub_co_matrix 중복 정리 + UNIQUE 제약
--
-- 문제: pair_key에 UNIQUE 제약이 없어 app.py의 upsert가 실제로는 INSERT처럼
--       동작 → 같은 페어가 여러 row로 분산되어 만남 횟수 통계가 부정확.
-- 해결: ① 동일 pair_key의 count를 합산해 1개 row로 병합, last_met은 가장 최근값으로
--       ② pair_key에 UNIQUE 제약 추가 → 이후 upsert가 정상 동작
-- ----------------------------------------------------------------------------

-- 백업 (롤백 대비)
CREATE TABLE IF NOT EXISTS bookclub_co_matrix_backup_004 AS
    SELECT * FROM bookclub_co_matrix;

-- 임시 테이블에 병합 결과 저장
CREATE TEMP TABLE _co_matrix_merged AS
SELECT
    (array_agg(id ORDER BY last_met DESC NULLS LAST))[1] AS keep_id,
    pair_key,
    SUM(count)::bigint AS total_count,
    MAX(last_met) AS latest_met
FROM bookclub_co_matrix
GROUP BY pair_key;

-- 살릴 row만 남기고 나머지 삭제
DELETE FROM bookclub_co_matrix
WHERE id NOT IN (SELECT keep_id FROM _co_matrix_merged);

-- 살린 row의 count/last_met을 합산값으로 갱신
UPDATE bookclub_co_matrix bm
SET count = m.total_count,
    last_met = m.latest_met
FROM _co_matrix_merged m
WHERE bm.id = m.keep_id;

-- 이제 안전하게 UNIQUE 제약 추가
ALTER TABLE bookclub_co_matrix
    ADD CONSTRAINT bookclub_co_matrix_pair_key_unique UNIQUE (pair_key);

-- ----------------------------------------------------------------------------
-- 2) members 인덱스 — 자주 eq() 조회되는 컬럼
-- ----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS members_name_idx ON public.members (name);
CREATE INDEX IF NOT EXISTS members_student_id_idx ON public.members (student_id) WHERE student_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS members_social_id_idx ON public.members (social_id) WHERE social_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS members_active_status_idx ON public.members (is_active, account_status);

-- ----------------------------------------------------------------------------
-- 3) notifications 조회 최적화 (관리자 알림 목록)
-- ----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS notifications_status_created_idx
    ON public.notifications (status, created_at DESC);

-- ----------------------------------------------------------------------------
-- 4) topic_events 활성 필터 (공개 페이지에서 is_active=true 조회 빈번)
-- ----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS topic_events_active_date_idx
    ON public.topic_events (is_active, meeting_date DESC);

-- ----------------------------------------------------------------------------
-- 5) attendance 일자별 조회 (월별 통계 등)
--
-- 기존: (user_id, meeting_date) UNIQUE — user_id 선행 쿼리에 효과적
-- 추가: meeting_date 단독 인덱스 — 특정 날짜 전원 조회용
-- ----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS attendance_meeting_date_idx
    ON public.attendance (meeting_date);

-- ----------------------------------------------------------------------------
-- 6) history (세미나 진행 기록) date 인덱스
-- ----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS history_date_idx ON public.history (date DESC);

-- ============================================================================
-- 완료 후 확인:
-- SELECT pair_key, COUNT(*) FROM bookclub_co_matrix GROUP BY pair_key HAVING COUNT(*) > 1;
-- → 결과 0건이어야 정상
-- ============================================================================


-- ===== 008_seminar_room_cache.sql =====

-- 008_seminar_room_cache.sql
-- 경북대 총동아리연합회 게시판(dongari.knu.ac.kr) 세미나실 예약 글 캐시
--
-- 관리자 페이지에서 달력으로 다른 동아리의 세미나실 예약 현황을 조회하기 위한 캐시.
-- 외부 사이트 크롤링 결과를 저장하며, status가 approved/rejected인 글은 종착 상태로 보고
-- 재크롤 시 상세 페이지를 다시 fetch 하지 않는다(pending만 재확인).
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.seminar_room_posts (
    wr_id            BIGINT PRIMARY KEY,                              -- gnuboard wr_id
    title            TEXT NOT NULL,
    club_name        TEXT,                                            -- 대괄호 안 동아리명
    room             TEXT,                                            -- '민주' | '통일' | '백호' | NULL
    dates            JSONB NOT NULL DEFAULT '[]'::jsonb,              -- ISO 날짜 문자열 배열
    status           TEXT NOT NULL DEFAULT 'pending',                 -- approved | pending | rejected
    post_url         TEXT,
    discovered_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_checked_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS seminar_room_posts_status_idx
    ON public.seminar_room_posts(status);

CREATE INDEX IF NOT EXISTS seminar_room_posts_dates_idx
    ON public.seminar_room_posts USING GIN(dates);


-- ===== 009_seminar_room_settings.sql =====

-- 009_seminar_room_settings.sql
-- 세미나실 예약 도우미 설정값 (싱글톤 1행)
--
-- 동아리명/전화번호/시간/목적/학기 시작·종료일 등을 관리자 UI 에서 직접 편집·저장한다.
-- env 변수 대신 DB 에 저장하여 코드 변경 없이 학기마다 갱신 가능.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.seminar_room_settings (
    id              INT PRIMARY KEY DEFAULT 1,
    club_name       TEXT NOT NULL DEFAULT '책 먹는 호반우',
    club_phone      TEXT NOT NULL DEFAULT '010-6509-3524',
    time_slot       TEXT NOT NULL DEFAULT '19:00~21:00',
    purpose         TEXT NOT NULL DEFAULT '동아리 세미나 진행',
    semester_start  DATE,
    semester_end    DATE,
    days_ahead_min  INT  NOT NULL DEFAULT 7,
    days_ahead_max  INT  NOT NULL DEFAULT 28,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT seminar_room_settings_singleton CHECK (id = 1)
);

-- 초기 1행 (기본값 + 현재 학기 종료일)
INSERT INTO public.seminar_room_settings (id, semester_end)
VALUES (1, DATE '2026-06-08')
ON CONFLICT (id) DO NOTHING;


commit;
