-- Remote migration version: 20260901134512
begin;

alter table public.topic_submissions
  add column if not exists member_id bigint
    references public.members(id) on delete set null,
  add column if not exists identity_kind text,
  add column if not exists edit_token_hash text,
  add column if not exists credential_version smallint not null default 1;

-- Only rows that were previously marked as member submissions and match one
-- unique member by both student ID and name can be backfilled automatically.
with unique_members as (
  select
    btrim(student_id) as student_id,
    min(id) as member_id,
    min(name) as member_name
  from public.members
  where nullif(btrim(student_id), '') is not null
  group by btrim(student_id)
  having count(*) = 1
)
update public.topic_submissions as submission
set member_id = matched.member_id
from unique_members as matched
where submission.member_id is null
  and submission.pin_code = 'MEMBER'
  and btrim(submission.student_id) = matched.student_id
  and btrim(submission.author_name) = btrim(matched.member_name);

-- Older member submissions often predate the student_id column. The current
-- production audit has no duplicate member names, but the HAVING guard keeps
-- this backfill safe if a duplicate is introduced before deployment.
with unique_member_names as (
  select
    btrim(name) as member_name,
    min(id) as member_id
  from public.members
  where nullif(btrim(name), '') is not null
  group by btrim(name)
  having count(*) = 1
)
update public.topic_submissions as submission
set member_id = matched.member_id
from unique_member_names as matched
where submission.member_id is null
  and submission.pin_code = 'MEMBER'
  and btrim(submission.author_name) = matched.member_name;

update public.topic_submissions
set identity_kind = case
  when member_id is not null then 'member'
  when pin_code = 'MEMBER' then 'legacy_member'
  else 'legacy_pin'
end
where identity_kind is null;

alter table public.topic_submissions
  alter column identity_kind set default 'legacy_pin',
  alter column identity_kind set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'topic_submissions_identity_kind_check'
      and conrelid = 'public.topic_submissions'::regclass
  ) then
    alter table public.topic_submissions
      add constraint topic_submissions_identity_kind_check
      check (identity_kind in ('member', 'guest', 'legacy_pin', 'legacy_member'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'topic_submissions_edit_token_hash_check'
      and conrelid = 'public.topic_submissions'::regclass
  ) then
    alter table public.topic_submissions
      add constraint topic_submissions_edit_token_hash_check
      check (edit_token_hash is null or edit_token_hash ~ '^[0-9a-f]{64}$');
  end if;
end
$$;

create unique index if not exists topic_submissions_event_member_uidx
  on public.topic_submissions(event_id, member_id)
  where member_id is not null;

create table if not exists public.topic_edit_attempts (
  id bigint generated by default as identity primary key,
  event_id uuid not null
    references public.topic_events(id) on delete cascade,
  request_hash text not null
    check (request_hash ~ '^[0-9a-f]{64}$'),
  succeeded boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists topic_edit_attempts_failed_lookup_idx
  on public.topic_edit_attempts(event_id, request_hash, created_at desc)
  where succeeded = false;

alter table public.topic_edit_attempts enable row level security;
revoke all on table public.topic_edit_attempts from public, anon, authenticated;
revoke all on sequence public.topic_edit_attempts_id_seq from public, anon, authenticated;
grant select, insert, update, delete on table public.topic_edit_attempts to service_role;
grant usage, select on sequence public.topic_edit_attempts_id_seq to service_role;

commit;
